[package]
name = "timely-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abomonation = "*"
abomonation_derive = "0.5.0"
chrono = "0.4.15"
nix = "0.19.0"
structopt = "0.3.20"
timely = "0.12.0"
